version: '3.8'
  
services:

  app:
    image: jetbrains/teamcity-server:2021.1.3
    restart: always
    ports:
      - 127.0.0.1:9013:8111
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs

  agent:
    image: jetbrains/teamcity-agent:2021.1.3
    restart: always
    environment:
      - AGENT_NAME=agent-zero
      - SERVER_URL=http://app:8111
    volumes:
      - ./agent-zero:/data/teamcity_agent/conf

