apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      environment: staging
      variant: staging
    includeTemplates: true
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ./../../base
