[tools]
minikube = "1.32.0"
pulumi = "3.104.2"
tilt = "0.33.11"
python = "3.12"

[tasks.kubernetes-up]
description = "Start a local Kubernetes cluster"
file = "kubernetes/k8s-start-cluster.sh"

[tasks.kubernetes-down]
description = "Stop the local Kubernetes cluster"
file = "kubernetes/k8s-stop-cluster.sh"

[tasks.kubernetes-delete]
description = "Delete the local kubernetes cluster"
file = "kubernetes/k8s-delete-cluster.sh"
