apiVersion: apps/v1
kind: Deployment
metadata:
  name: transposer-backend
  labels:
    app: transposer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transposer-backend
  template:
    metadata:
      labels:
        app: transposer-backend
    spec:
      containers:
      - name: transposer-backend
        image: transposer-backend
        envFrom:
          - configMapRef:
              name: transposer-backend-config
        ports:
          - containerPort: 8000
            protocol: TCP
            name: api
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
