kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-sandbox
networking:
  apiServerAddress: "127.0.0.1"
  podSubnet: "10.100.0.0/16"
  serviceSubnet: "10.101.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.20.7@sha256:688fba5ce6b825be62a7c7fe1415b35da2bdfbb5a69227c499ea4cc0008661ca
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 10080
      listenAddress: 127.0.0.1
      protocol: TCP
    - containerPort: 443
      hostPort: 10443
      listenAddress: 127.0.0.1
      protocol: TCP
  - role: worker
    image: kindest/node:v1.20.7@sha256:688fba5ce6b825be62a7c7fe1415b35da2bdfbb5a69227c499ea4cc0008661ca
#  - role: worker
#    image: kindest/node:v1.20.7@sha256:688fba5ce6b825be62a7c7fe1415b35da2bdfbb5a69227c499ea4cc0008661ca
#  - role: worker
#    image: kindest/node:v1.20.7@sha256:688fba5ce6b825be62a7c7fe1415b35da2bdfbb5a69227c499ea4cc0008661ca

