apiVersion: v1
kind: Namespace
metadata:
  name: testing-omvmt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache-stateful-testing-omvmt
  namespace: testing-omvmt
spec:
  selector:
    matchLabels:
      app: apache-testing-omvmt
  serviceName: apache-svc
  replicas: 0
  template:
    metadata:
      labels:
        app: apache-testing-omvmt
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: www
          mountPath: /var/www/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: testing-omvmt
  labels:
    app: apache-testing-omvmt
spec:
  clusterIP: None
  selector:
    app: apache-testing-omvmt
  ports:
  - name: web
    port: 80
