apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cluster-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-prometheus
subjects:
- kind: ServiceAccount
  name: cluster-prometheus
  namespace: cluster-prometheus
