apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim2
  namespace: testing-fdrr5
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-1abc4f6f-3f2a-4a96-9ed9-292e185bf55d