apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink }}
