apiVersion: v1
kind: Pod
metadata:
  name: cloudbox
  namespace: default
  labels:
    name: cloudbox
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: cloudbox
    image: chronicc/cloudbox:0.2.2
    resources:
      limits:
        cpu: 500m
        memory: '0.5Gi'
    args:
    - sleep
