apiVersion: apps/v1
kind: Deployment
metadata:
  name: transposer-frontend
  labels:
    app: transposer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transposer-frontend
  template:
    metadata:
      labels:
        app: transposer-frontend
    spec:
      containers:
      - name: transposer-frontend
        image: transposer-frontend
        envFrom:
          - configMapRef:
              name: transposer-frontend-config
        ports:
          - containerPort: 80
            protocol: TCP
            name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
