apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      variant: offline
    includeTemplates: true
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ./../../base
